In [8]:
import numpy
n = numpy.arange(27)
print(type(n))
n

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
n.reshape(3, 3, 3) // 3D array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
n.reshape(3, 9) //2D Array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [25]:
import cv2
im_g=cv2.imread("Untitled.jpg",1)
cv2.imwrite("CreateImageFromPandaArray.jpg",im_g)
print(im_g)

[[[149 154 153]
  [118 107 123]
  [150 161 151]
  [144 156 144]
  [157 153 164]
  [138 150 152]
  [106 118 106]
  [167 152 160]
  [161 150 166]
  [238 245 210]
  [ 54  95  34]
  [135 143 132]]

 [[222  16 121]
  [251 233 250]
  [  0 228 242]
  [255 249 255]
  [ 11 234 248]
  [250 255 249]
  [  0 235 255]
  [254 246 246]
  [216 215 224]
  [124 134 134]
  [ 97  99  79]
  [ 39  97   0]]

 [[236 194 205]
  [212 106 153]
  [210  20 145]
  [243 187 198]
  [255 255 254]
  [  0 231 255]
  [255 250 248]
  [  0 248 255]
  [250 249   9]
  [203 202 206]
  [198 204 199]
  [100 112 106]]

 [[111 209 119]
  [161 228 159]
  [255 253 255]
  [230 131 177]
  [241 253 133]
  [255 255 237]
  [243 255 181]
  [255 242   0]
  [247 255 195]
  [252 223 239]
  [255 215 236]
  [249 255 251]]

 [[165 225 177]
  [233 244 255]
  [240 250 238]
  [243 192 206]
  [252 255 127]
  [243 251 210]
  [245 255 181]
  [255 254 251]
  [145 238 247]
  [244 175 166]
  [255  81  90]
  [255 255 245]]

 [[255 255 247]
  [118 206 253

In [27]:
im_g[0:2, 2:4]

array([[[150, 161, 151],
        [144, 156, 144]],

       [[  0, 228, 242],
        [255, 249, 255]]], dtype=uint8)

In [28]:
// Image Stacking is the next one


SyntaxError: invalid syntax (Temp/ipykernel_45736/4124583694.py, line 1)

In [31]:
ims=numpy.hstack((im_g, im_g))
ims

array([[[149, 154, 153],
        [118, 107, 123],
        [150, 161, 151],
        [144, 156, 144],
        [157, 153, 164],
        [138, 150, 152],
        [106, 118, 106],
        [167, 152, 160],
        [161, 150, 166],
        [238, 245, 210],
        [ 54,  95,  34],
        [135, 143, 132],
        [149, 154, 153],
        [118, 107, 123],
        [150, 161, 151],
        [144, 156, 144],
        [157, 153, 164],
        [138, 150, 152],
        [106, 118, 106],
        [167, 152, 160],
        [161, 150, 166],
        [238, 245, 210],
        [ 54,  95,  34],
        [135, 143, 132]],

       [[222,  16, 121],
        [251, 233, 250],
        [  0, 228, 242],
        [255, 249, 255],
        [ 11, 234, 248],
        [250, 255, 249],
        [  0, 235, 255],
        [254, 246, 246],
        [216, 215, 224],
        [124, 134, 134],
        [ 97,  99,  79],
        [ 39,  97,   0],
        [222,  16, 121],
        [251, 233, 250],
        [  0, 228, 242],
        [255, 249, 255]